### ISSUE TITLE
failed to run custom build command for `openssl-sys v0.6.2`

### ISSUE THREAD

**Issue by denpatin** [mkpankov/rust-phonebook#2]
Hi there once again,

I've pulled the newest version of this repo, tried to execute `cargo install`, however the following's been thrown out:

<img width="1272" alt="screen shot 2016-07-12 at 5 28 05 pm" src="https://cloud.githubusercontent.com/assets/1271040/16770680/7a7fc672-4856-11e6-976e-8dc3e006af73.png">
<img width="1272" alt="screen shot 2016-07-12 at 5 28 35 pm" src="https://cloud.githubusercontent.com/assets/1271040/16770679/7a7ec77c-4856-11e6-9760-b14196733712.png">

Apparently the problem isn't at your side, however maybe I'm doing something wrong with Cargo or your repo... I presume you've successfully built the rust-phonebook so the problem must occur somewhere at mine.

**Comment by mkpankov** [comment]
Seems you're on MacOS. You probably need to follow instructions to setup OpenSSL for Rust on MacOS, [like this](https://github.com/sfackler/rust-openssl#osx). Also, [this script](https://gist.github.com/e-oz/4c86ec6920db58eae2a5555f31bbd3c5) might be useful.

BTW, I wouldn't `cargo install` the project. Just usual `cargo build` in enough - compiled binary will be in `target` directory.

**Comment by denpatin** [comment]
@mkpankov I've already had OpenSSL on Mac, however it wasn't correctly linked. Thanks, that works!
